name: wise_dev
description: Wise Dev Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^4.1.1
  flutter_bloc: ^8.0.0
  freezed_annotation: ^2.0.3
  firebase_core: ^1.10.6
  intl: ^0.17.0

  repository:
    path: packages/repository
  entity:
    path: packages/entity

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  flutter_svg: ^1.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.otf
        - asset: assets/fonts/PlayfairDisplay-Bold.otf
        - asset: assets/fonts/PlayfairDisplay-Italic.otf
        - asset: assets/fonts/Poppins-Regular.otf