name: codwise
description: your daily dose of tech wisdom and inspiration

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  go_router: ^8.0.5
  flutter_bloc: ^8.0.0
  freezed_annotation: ^2.0.3
  firebase_core: ^2.14.0
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.5

  repository:
    path: packages/repository
  entity:
    path: packages/entity

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/quotes/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.otf
        - asset: assets/fonts/PlayfairDisplay-Bold.otf
        - asset: assets/fonts/PlayfairDisplay-Italic.otf
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf