name: repository
description: Dart package which holds all repositories
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  intl: ^0.17.0
  csv: ^5.0.1
  entity:
    path: ../entity
